apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trip-canvas
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: trip-canvas.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trip-canvas
                port:
                  number: 80
