apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trip-canvas-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seonwook61/travleCanvas.git
    targetRevision: main
    path: deploy/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: trip-canvas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
